In [16]:
import pandas as pd

In [17]:
label = pd.read_csv('../csv/Batch 300 call đã gán nhãn_M3B.csv')

In [18]:
label.head()

,file_name,criterion_name,audit_result,reason,group
0,1686296155875_3755_810349533873_525039757.mp3,Amount,UN,NaN,Collection
1,1684482083958_3770_810983451276_516462765.mp3,Identification of client,Yes,NaN,Collection
2,1684482083958_3770_810983451276_516462765.mp3,Reason of the call,Yes,NaN,Collection
3,1684482083958_3770_810983451276_516462765.mp3,Will you pay?,Yes,NaN,Collection
4,1684482083958_3770_810983451276_516462765.mp3,When,NaN,KH cúp ngang,Collection

In [19]:
label_cr = label[label['criterion_name'] == "Call Result"]
label_cr

,file_name,criterion_name,audit_result,reason,group
24,1684482083958_3770_810983451276_516462765.mp3,Call Result,Nopay,NaN,Collection
49,1684482109334_3771_810932104194_516462776.mp3,Call Result,Call không hợp tác,NaN,Collection
74,1684484668825_3776_810365496726_516470077.mp3,Call Result,Undefined,NaN,Collection
99,1684484804994_3753_810989015916_516470478.mp3,Call Result,Willpay,NaN,Collection
124,1684485272349_3648_810939424196_516471469.mp3,Call Result,Undefined,NaN,Collection
...,...,...,...,...,...
7397,1684997958420_3732_810968502918_517496149.mp3,Call Result,Nopay,NaN,Collection
7422,1684999898682_3739_810387660098_517502999.mp3,Call Result,Nopay,NaN,Collection
7447,1685003537288_3739_810886013317_517513797.mp3,Call Result,Willpay,NaN,Collection
7472,1685064372290_3743_810931516538_517542970.mp3,Call Result,Willpay,NaN,Collection
7497,1685065025516_3730_810919274306_517547091.mp3,Call Result,Willpay,NaN,Collection

In [20]:
cr_file = pd.read_csv("../csv/compare_callResultAI.csv")
cr_file

,name,Criterion Name,Expected Result,Actual Result,callResultAI
0,1684482083958_3770_810983451276_516462765.mp3,Contain all information,no,NaN,nopay
1,1684482109334_3771_810932104194_516462776.mp3,Contain all information,no,No,nopay
2,1684484668825_3776_810365496726_516470077.mp3,Contain all information,no,NaN,nopay
3,1684484804994_3753_810989015916_516470478.mp3,Contain all information,no,NaN,willpay
4,1684485272349_3648_810939424196_516471469.mp3,Contain all information,no,NaN,undefined
...,...,...,...,...,...
295,1686275888826_3729_810973322412_519911491.mp3,Contain all information,yes,Yes,undefined
296,1686276029433_3734_810981456551_519912816.mp3,Contain all information,yes,Yes,willpay
297,1686279460634_3732_810909757150_519942265.mp3,Contain all information,no,NaN,willpay
298,1686285301787_3769_810337445113_519982400.mp3,Contain all information,no,NaN,nopay
299,1686296155875_3755_810349533873_525039757.mp3,Contain all information,no,NaN,nopay

In [22]:
label_cr["callResultAI"] = cr_file['callResultAI']

C:\Users\admin\AppData\Local\Temp\ipykernel_15848\1591862247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label_cr["callResultAI"] = cr_file['callResultAI']

In [23]:
label_cr.to_csv('../csv/label_cr.csv', index=False)

In [25]:
label_cr = pd.read_csv('../csv/label_cr.csv')
label_cr

,file_name,criterion_name,audit_result,reason,group,callResultAI
0,1684482083958_3770_810983451276_516462765.mp3,Call Result,Nopay,NaN,Collection,willpay
1,1684482109334_3771_810932104194_516462776.mp3,Call Result,Call không hợp tác,NaN,Collection,undefined
2,1684484668825_3776_810365496726_516470077.mp3,Call Result,Undefined,NaN,Collection,willpay
3,1684484804994_3753_810989015916_516470478.mp3,Call Result,Willpay,NaN,Collection,undefined
4,1684485272349_3648_810939424196_516471469.mp3,Call Result,Undefined,NaN,Collection,nopay
...,...,...,...,...,...,...
295,1684997958420_3732_810968502918_517496149.mp3,Call Result,Nopay,NaN,Collection,NaN
296,1684999898682_3739_810387660098_517502999.mp3,Call Result,Nopay,NaN,Collection,NaN
297,1685003537288_3739_810886013317_517513797.mp3,Call Result,Willpay,NaN,Collection,NaN
298,1685064372290_3743_810931516538_517542970.mp3,Call Result,Willpay,NaN,Collection,NaN
299,1685065025516_3730_810919274306_517547091.mp3,Call Result,Willpay,NaN,Collection,NaN